### ISSUE TITLE
Publish the extension on Open VSX

### ISSUE THREAD

**Issue by moigagoo** [pragmagic/vscode-nim#176]
Open VSX is a an open, vendor-neutral repository of VSCode extensions.

It is used by editors other than VSCode but that want to support its extension protocol, like Onivim2.

Intructions: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by omentic** [comment]
For those unaware, the [currently available Nim extension in the Open VSX registry](https://open-vsx.org/extension/nimsaem/nimvscode) is a rewrite of this one in Nim itself, and should provide a similar feature set (but it would be nice to have both!)

**Comment by mrhyperbit** [comment]
Dear extension author,
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by omentic** [comment]
This extension was superseded by a dogfood-ed version at https://github.com/saem/vscode-nim. If anything, it would be good to *remove* this extension from the Microsoft marketplace.
