### ISSUE TITLE
Suggestions when writing comments

### ISSUE THREAD

**Issue by dom96** [pragmagic/vscode-nim#33]
Not sure if this is an issue with this plugin or VS code. But getting suggestions in comments is absolutely infuriating sometimes.

In fact, I had to just disable suggestions because seeing them pop up so often is simply too distracting.

**Comment by RSDuck** [comment]
As far I can tell the issue is related to nimsuggest. On request it still suggests symbols although the cursor is located in a comment. This would be easy to fix from plugin side, but in my opinion it is a problem with nimsuggest.

A similar issue would be that nimsuggest suggests the usage of a nearby procedure call when the cursor actually located in a tuple

**Comment by dom96** [comment]
I would say it's a bug in both. VS Code shouldn't request suggestions when the cursor is inside a comment.

**Comment by RSDuck** [comment]
In this case every editor has to implement the same feature. I think it would be smarter to keep the plugins as thin as possible and centralize the whole completion progress within nimsuggest.

**Comment by RSDuck** [comment]
Both Nimsuggest(https://github.com/nim-lang/Nim/commit/1887390b0f5e768e41aa220ea34f8059de5862b0) and VSCode(https://code.visualstudio.com/updates/v1_11#_intellisense-in-comments) now take care of it, so I think this issue can be closed.
