### ISSUE TITLE
Toggle line comment stopped working in .nim files after 0.5.15 update

### ISSUE THREAD

**Issue by yay** [pragmagic/vscode-nim#35]
Toggle line comment action stopped working either from the menu or via the cmd+/ shortcut.

**Comment by yay** [comment]
To rollback (on a mac)
1) download the previous version here: `https://kosz78.gallery.vsassets.io/_apis/public/gallery/publisher/kosz78/extension/nim/0.5.14/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage`
2) Unpack the Microsoft.VisualStudio.Services.VSIXPackage (it's actually an archive)
3) Copy the `extension` directory to `/Users/<username>/.vscode/extensions
4) rename the copied directory to `kosz78.nim-0.5.14`

You are welcome :)

**Comment by RSDuck** [comment]
I think it's because here: https://github.com/pragmagic/vscode-nim/commit/83182d184ab20e1bee7ded13adbb428117abc2af#diff-c37c751acafdb95f403dbb4c2b3c12beL8
was defined how a comment looks like, but now(https://github.com/pragmagic/vscode-nim/commit/83182d184ab20e1bee7ded13adbb428117abc2af#diff-f8bd73a6b48ee0c6e1013824c58e6cf1R40) it's gone.
